model:
  target: models.DBECFuse
  params:
    in_channels: 1
    channel_mults: [16, 16]
  pretrained: weights/DBECFuse/alpha=5_mu=1.0.pth

train:
  accumulation_steps: 64
  epochs: 500
  optimizer:
    target: torch.optim.Adam
    params:
      lr: 1.e-3

dataset:
  ratio: [0.8, 0.2]
  batch_size: 1
  shuffle: true
  url:
    MSRS: E:/projects/dataset/MSRS
    TNO: E:/projects/dataset/TNO
    MFN: E:/projects/yolov9/data/ir_det_dataset/Images